CREATE TABLE USUARIO(
id_usuario NUMBER(4,0) GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 1),
nombreCompleto VARCHAR2(60) NOT NULL,
correo VARCHAR2(50) NOT NULL,
numero NUMBER(10,0) NOT NULL,
nombreUser VARCHAR2(15) NOT NULL,
contrasena  VARCHAR2(15) NOT NULL,
fecha_creacion DATE NOT NULL)

CREATE TABLE PERSONA(
rut VARCHAR2(13) NOT NULL,
nombre VARCHAR2(25) NOT NULL)

CREATE TABLE REGISTRO(
id_registro NUMBER(4,0) GENERATED ALWAYS AS IDENTITY (START WITH 3000 INCREMENT BY 1),
rut VARCHAR2(13) NOT NULL,
id_usuario NUMBER(4,0) NOT NULL,
fecha DATE NOT NULL,
tipo_registro VARCHAR2(8) NOT NULL)


--INTEGRIDAD DE ENTIDAD
ALTER TABLE USUARIO
ADD CONSTRAINT PK_USUARIO PRIMARY KEY (id_usuario);

ALTER TABLE REGISTRO
ADD CONSTRAINT PK_REGISTRO PRIMARY KEY (id_registro);

ALTER TABLE PERSONA
ADD CONSTRAINT PK_PERSONA PRIMARY KEY (rut);


--INTEGRIDAD REFERENCIAL

ALTER TABLE REGISTRO
ADD CONSTRAINT FK_REGISTRO_PERSONA FOREIGN KEY (rut)
REFERENCES PERSONA(rut);

ALTER TABLE REGISTRO
ADD CONSTRAINT FK_REGISTRO_USUARIO FOREIGN KEY (id_usuario)
REFERENCES USUARIO(id_usuario);


--Integridad de dominio
ALTER TABLE REGISTRO
ADD CONSTRAINT CK_tipoRegistro CHECK (tipo_registro IN ('INGRESO','SALIDA'));




