CREATE TABLE USUARIO(
id_usuario NUMBER(4,0) GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 1),
nombreUser VARCHAR2(15) NOT NULL,
contrasena  VARCHAR2(15) NOT NULL,
fecha_creacion DATE NOT NULL)

CREATE TABLE PERSONA(
id_persona NUMBER(4,0) GENERATED ALWAYS AS IDENTITY(START WITH 2000 INCREMENT BY 1),
rut VARCHAR2(10) NOT NULL,
nombre VARCHAR2(25) NOT NULL,
estado VARCHAR2(8) NOT NULL)

CREATE TABLE REGISTRO(
id_registro NUMBER(4,0) GENERATED ALWAYS AS IDENTITY (START WITH 3000 INCREMENT BY 1),
id_persona NUMBER(4,0) NOT NULL,
id_usuario NUMBER(4,0) NOT NULL,
fecha_hora DATE NOT NULL,
tipo_registro VARCHAR2(8) NOT NULL)


--INTEGRIDAD DE ENTIDAD
ALTER TABLE USUARIO
ADD CONSTRAINT PK_USUARIO PRIMARY KEY (id_usuario);

ALTER TABLE REGISTRO
ADD CONSTRAINT PK_REGISTRO PRIMARY KEY (id_registro);

ALTER TABLE PERSONA
ADD CONSTRAINT PK_PERSONA PRIMARY KEY (id_persona);

--Integridad de dominio
ALTER TABLE REGISTRO
ADD CONSTRAINT CK_tipoRegistro CHECK (tipo_registro IN ('INGRESO','SALIDA'));

ALTER TABLE PERSONA
ADD CONSTRAINT CK_estado CHECK (estado IN ('DENTRO','FUERA'));




