-- TABLAS DE LAS ENTIDADES

-- TABLA PERSONA
CREATE TABLE PERSONA(
    rut VARCHAR2(13) NOT NULL,
    nombre VARCHAR2(25) NOT NULL
);

-- TABLA REGISTRO
CREATE TABLE REGISTRO(
    id_registro NUMBER(4,0) GENERATED ALWAYS AS IDENTITY (START WITH 3000 INCREMENT BY 1),
    rut VARCHAR2(13) NOT NULL,
    id_usuario NUMBER(4,0) NOT NULL,
    fecha DATE NOT NULL,
    hora VARCHAR2(8) NOT NULL,
    tipo_registro VARCHAR2(8) NOT NULL
);

-- TABLA USUARIO
CREATE TABLE USUARIO(
    id_usuario NUMBER(4,0) GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    nombreCompleto VARCHAR2(60) NOT NULL,
    correo VARCHAR2(50) NOT NULL,
    numero NUMBER(10,0) NOT NULL,
    nombreUser VARCHAR2(15) NOT NULL,
    contrasena  VARCHAR2(15) NOT NULL,
    fecha_creacion DATE NOT NULL
);

-- TABLA USUARIO_ROL
CREATE TABLE USUARIO_ROL(
    ID_UR NUMBER(4,0) GENERATED ALWAYS AS IDENTITY (START WITH 2000 INCREMENT BY 1),
    id_usuario NUMBER(4,0) NOT NULL,
    id_rol  NUMBER(4,0) NOT NULL
);

-- TABLA ROL
CREATE TABLE ROL(
   id_rol NUMBER(4,0) GENERATED ALWAYS AS IDENTITY (START WITH 4000 INCREMENT BY 1),
   nombre_rol   VARCHAR2(30)    NOT NULL,
   fecha_creacion   DATE NOT NULL
);

-- TABLA ROL_PERMISO
CREATE TABLE ROL_PERMISO(
    ID_RP NUMBER(4,0) GENERATED ALWAYS AS IDENTITY (START WITH 6000 INCREMENT BY 1),
    id_rol NUMBER(4,0) NOT NULL,
    id_permiso  NUMBER(4,0) NOT NULL
);

-- TABLA PERMISO
CREATE TABLE PERMISO(
    id_permiso  NUMBER(4,0) GENERATED ALWAYS AS IDENTITY (START WITH 5000 INCREMENT BY 1),
    nomber_permiso  VARCHAR2(30)    NOT NULL
);

--INTEGRIDAD DE ENTIDAD
ALTER TABLE USUARIO
ADD CONSTRAINT PK_USUARIO PRIMARY KEY (id_usuario);

ALTER TABLE REGISTRO
ADD CONSTRAINT PK_REGISTRO PRIMARY KEY (id_registro);

ALTER TABLE PERSONA
ADD CONSTRAINT PK_PERSONA PRIMARY KEY (rut);

ALTER TABLE ROL
ADD CONSTRAINT PK_ROL PRIMARY KEY (id_rol);

ALTER TABLE ROL_PERMISO
ADD CONSTRAINT PK_ROL_PERMISO PRIMARY KEY (ID_RP);

ALTER TABLE USUARIO_ROL
ADD CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (ID_UR);

ALTER TABLE PERMISO
ADD CONSTRAINT PK_PERMISO PRIMARY KEY (id_permiso);


--INTEGRIDAD REFERENCIAL

ALTER TABLE REGISTRO
ADD CONSTRAINT FK_REGISTRO_PERSONA FOREIGN KEY (rut)
REFERENCES PERSONA(rut);

ALTER TABLE REGISTRO
ADD CONSTRAINT FK_REGISTRO_USUARIO FOREIGN KEY (id_usuario)
REFERENCES USUARIO(id_usuario);

ALTER TABLE USUARIO_ROL
ADD CONSTRAINT FK_USUARIOROL_USUARIO FOREIGN KEY(id_usuario)
REFERENCES USUARIO(id_usuario);

ALTER TABLE USUARIO_ROL
ADD CONSTRAINT FK_USUARIOROL_ROL FOREIGN KEY (id_rol)
REFERENCES ROL(id_rol);

ALTER TABLE ROL_PERMISO
ADD CONSTRAINT FK_ROLPERMISO_ROL FOREIGN KEY (id_rol)
REFERENCES ROL(id_rol);

ALTER TABLE ROL_PERMISO
ADD CONSTRAINT FK_ROLPERMISO_PERMISO FOREIGN KEY (id_permiso)
REFERENCES PERMISO(id_permiso);

--Integridad de dominio
ALTER TABLE REGISTRO
ADD CONSTRAINT CK_tipoRegistro CHECK (tipo_registro IN ('INGRESO','SALIDA'));



